export * from './schema';
export { getDb } from './client';

export type { User, NewUser } from './schema/users';
export type { Role, Permission, UserRole } from './schema/roles';
export type { Session } from './schema/sessions';
export type { AuditLog } from './schema/audit';
export type { VisitorLog, NewVisitorLog } from './schema/visitors';
export type { Notification, NewNotification, NotificationTemplate } from './schema/notifications';
export type { Program, Course, Module, Lesson, LessonMaterial } from './schema/learning';
export type { Enrollment, ProgressTracking } from './schema/enrollments';
export type { Assignment, Submission, Grade, Assessment, AssessmentQuestion, AssessmentAttempt, AssessmentResponse } from './schema/assessments';
export type { AttendanceRecord } from './schema/attendance';
export type { Certificate } from './schema/certificates';
export type { Conversation, Message } from './schema/messaging';
export type { Portfolio, PortfolioProject } from './schema/portfolios';
export type { Employer, JobListing, JobApplication, JobInterview, FreelanceGig, GigApplication } from './schema/marketplace';
export type { AlumniProfile, Placement } from './schema/alumni';
export type { Contact } from './schema/crm';
export type { Deal } from './schema/crm';
export type { Project } from './schema/projects';
export type { ProjectTask } from './schema/projects';
export type { Milestone } from './schema/projects';
export type { ProjectTeamMember } from './schema/projects';
export type { SupportTicket } from './schema/tickets';
export type { TicketMessage } from './schema/tickets';
export type { Contract } from './schema/contracts';
export type { Invoice } from './schema/invoices';
export type { InvoiceLineItem } from './schema/invoices';
export type { Application, ApplicationDocument, Offer } from './schema/admissions';
export type { Transaction, ExpenseClaim, Budget, Account } from './schema/finance';
export type { Employee, LeaveRequest, Department, Branch, StaffAttendance, PerformanceReview } from './schema/hr';
export type { InventoryItem, AssetTrack, StockMovement } from './schema/inventory';
export type { Supplier, PurchaseOrder, PurchaseOrderItem } from './schema/procurement';
export type { ForumCategory, ForumThread, ForumPost, Group, GroupMember, Event, EventRegistration, Scholarship, ScholarshipApplication, MentorshipRelation, Partnership, VolunteerOpportunity, VolunteerSignup, Donation } from './schema/community';
export type { Room, NewRoom, RoomBooking, NewRoomBooking, WorkOrder, NewWorkOrder } from './schema/facilities';
